import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

const Chatpage = () => {
  return <div>Chatpage</div>;
};

export default Chatpage;
